{
 "title": "Spark Metrics",
 "time": { "from": "2018-11-15T00:23:06.000Z", "to": "2018-11-15T01:15:04.000Z" },
 "panels": [
  {
   "title": "Event Hub Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "let results = SparkMetric_CL\n| where $__timeFilter(TimeGenerated)   \n| where name_s contains \"executor.jvmGCTime\" \n| extend sname=split(name_s, \".\") \n| project TimeGenerated , jvmgcTime=count_d  ,  executor=strcat(sname[0],sname[1]) ,name_s\n| join kind= inner (\n    SparkMetric_CL\n| where name_s contains \"executor.RunTime\"\n| extend sname=split(name_s, \".\") \n| project TimeGenerated , runTime=count_d  ,  executor=strcat(sname[0],sname[1]) ,name_s\n) on executor, TimeGenerated;\nresults\n| project TimeGenerated, jvmcpuusage=(jvmgcTime/runTime)*100, executor",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Outgoing Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "OUTMSGS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Event Hub IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Bytes",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "IncomingBytes",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "OutGoing Bytes",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "OutgoingBytes",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "SparkMetric_CL \n| where $__timeFilter(TimeGenerated)\n| where name_s contains \"driver.DAGScheduler.job.allJobs\"\n| order by TimeGenerated asc nulls last ",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "SparkMetric_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where name_s contains \"completetasks\"\r\n| project TimeGenerated , taskscompleted=value_d\r\n| order by TimeGenerated nulls last ",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "% Executor CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "let results = SparkMetric_CL \n| where $__timeFilter(TimeGenerated) \n| where name_s contains \"executor.cpuTime\" \n| extend sname=split(name_s, \".\") \n| project TimeGenerated , cpuTime=count_d/1000000  ,  executor=strcat(sname[0],sname[1]) ,name_s\n| join kind= inner (\n    SparkMetric_CL\n| where $__timeFilter(TimeGenerated) \n| where name_s contains \"executor.RunTime\"\n| extend sname=split(name_s, \".\") \n| project TimeGenerated , runTime=count_d  ,  executor=strcat(sname[0],sname[1]) ,name_s\n) on executor, TimeGenerated;\nresults\n| extend cpuUsage=(cpuTime/runTime)*100\n| summarize ExecutorCpuTime = percentile(cpuUsage,50) by bin(TimeGenerated, 1m), executor\n| order by TimeGenerated asc nulls last   \n",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "% Jvm CPU / Executor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "let results = SparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| where name_s contains \"executor.jvmGCTime\" \n| extend sname=split(name_s, \".\") \n| project TimeGenerated , jvmgcTime=count_d , executor=strcat(sname[0],sname[1]) ,name_s\n| join kind= inner (\nSparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| where name_s contains \"executor.RunTime\"\n| extend sname=split(name_s, \".\") \n| project TimeGenerated , runTime=count_d , executor=strcat(sname[0],sname[1]) ,name_s\n) on executor, TimeGenerated;\nresults\n| extend JvmcpuUsage=(jvmgcTime/runTime)*100\n| summarize JvmCpuTime = percentiles(JvmcpuUsage,25, 50, 75, 90) by bin(TimeGenerated, 1m), executor\n| order by TimeGenerated asc nulls last\n| render timechart  \n",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Streaming Throughput / Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Rows / Sec" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "taxirides_CL\n| where $__timeFilter(timestamp_t)\n| where  isnotempty(mdc_id_g)\n| extend sname=strcat(mdc_id_g,\"-\",\"ProcRowsSec\") \n| summarize any(mdc_procRowsPerSecond_d)  by bin(timestamp_t, 1m), sname\n| order by timestamp_t asc  nulls last ",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "taxirides_CL\n| where $__timeFilter(timestamp_t)\n| where  isnotempty(mdc_id_g)\n| extend sname=strcat(mdc_id_g,\"-\",\"triggerExec\") \n| summarize any(mdc_durationms_triggerExecution_d)  by bin(timestamp_t, 1m), sname\n| order by timestamp_t asc  nulls last \n",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "taxirides_CL\n| where $__timeFilter(timestamp_t)\n| where  isnotempty(mdc_id_g)\n| extend sname=strcat(mdc_id_g,\"-\",\"InputRowsSec\") \n| summarize any(mdc_inputRowsPerSecond_d)  by bin(timestamp_t, 1m), sname\n| order by timestamp_t asc  nulls last ",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "% Deserialize Cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "let results = SparkMetric_CL \n| where $__timeFilter(TimeGenerated)\n| where name_s contains \"executor.deserializetime\" \n| extend sname=split(name_s, \".\") \n| project TimeGenerated , desetime=count_d , executor=strcat(sname[0],sname[1]) ,name_s\n| join kind= inner (\nSparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| where name_s contains \"executor.RunTime\"\n| extend sname=split(name_s, \".\") \n| project TimeGenerated , runTime=count_d , executor=strcat(sname[0],sname[1]) ,name_s\n) on executor, TimeGenerated;\nresults\n| extend deseUsage=(desetime/runTime)*100\n| summarize deSerializationCpuTime=percentiles(deseUsage,25, 50, 75, 100) by bin(TimeGenerated, 1m), executor\n| order by TimeGenerated asc nulls last ",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "% Serialize Cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "let results = SparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| where name_s contains \"executor.resultserializationtime\" \n| extend sname=split(name_s, \".\") \n| project TimeGenerated , setime=count_d , executor=strcat(sname[0],sname[1]) ,name_s\n| join kind= inner (\nSparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| where name_s contains \"executor.RunTime\"\n| extend sname=split(name_s, \".\") \n| project TimeGenerated , runTime=count_d , executor=strcat(sname[0],sname[1]) ,name_s\n) on executor, TimeGenerated;\nresults\n| extend serUsage=(setime/runTime)*100\n| summarize SerializationCpuTime=percentiles(serUsage,25, 50, 75, 100) by bin(TimeGenerated, 1m), executor\n| order by TimeGenerated asc nulls last\n| render timechart ",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Running Executors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "# Running Executors" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "SparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| extend sname=split(name_s, \".\")\n| extend executor=strcat(sname[0],sname[1]) \n| summarize NumExecutors=dcount(executor)  by bin(TimeGenerated,  1m)\n| order by TimeGenerated asc  nulls last ",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "File System IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes", "label": "File System Bytes Write" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "SparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| extend sname=split(name_s, \".\")\n| where  name_s  contains \"executor.filesystem.file.write_bytes\" \n| summarize FileSystemWriteBytes=any(value_d)  by bin(TimeGenerated,  1m), strcat(sname[0],sname[1])\n| order by TimeGenerated asc  nulls last \n| render timechart",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Shuffle IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 31 },
   "yaxes": [
    { "format": "decbytes", "label": "Shuffle Bytes Write" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "SparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| where  name_s  contains \"executor.shuffleBytesWritten\"\n| extend sname=split(name_s, \".\")  \n| summarize ShuffleBytesWrite=any(count_d)  by bin(TimeGenerated,  1m), strcat(sname[0],sname[1]) \n| order by TimeGenerated asc  nulls last ",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Shuffle Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 31 },
   "yaxes": [
    { "format": "bytes", "label": "ShuffleClientDirectMemory" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "SparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| where  name_s  contains \"ExternalShuffle.shuffle-client.usedDirectMemory\"\n| extend sname=split(name_s, \".\")  \n| summarize any(value_d)  by bin(TimeGenerated,  1m), strcat(sname[0],sname[1]) \n| order by TimeGenerated asc  nulls last",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "File System IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes", "label": "File System Bytes Read" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "SparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| extend sname=split(name_s, \".\")\n| where  name_s  contains \"executor.filesystem.file.read_bytes\" \n| summarize FileSystemWriteBytes=any(value_d)  by bin(TimeGenerated,  1m), strcat(sname[0],sname[1])\n| order by TimeGenerated asc  nulls last \n| render timechart",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Shuffle IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 38 },
   "yaxes": [
    { "format": "decbytes", "label": "Shuffle Bytes Read" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "SparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| where  name_s  contains \"executor.shuffleTotalBytesRead\"\n| extend sname=split(name_s, \".\")  \n| summarize ShuffleBytesWrite=any(count_d)  by bin(TimeGenerated,  1m), strcat(sname[0],sname[1]) \n| order by TimeGenerated asc  nulls last ",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Shuffle Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 38 },
   "yaxes": [
    { "format": "bytes", "label": "ShuffleHeapMemory" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "SparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| where  name_s  contains \"shuffle-client.usedHeapMemory\"\n| extend sname=split(name_s, \".\")  \n| summarize any(value_d)  by bin(TimeGenerated,  1m), strcat(sname[0],sname[1]) \n| order by TimeGenerated asc  nulls last",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "taxirides_CL\n| where $__timeFilter(timestamp_t)\n| where Level contains \"Error\"\n| summarize CountExceptions=count(Level) , max(timestamp_t)    \n",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Shuffle Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 45 },
   "yaxes": [
    { "format": "bytes", "label": "ShuffleMemorySpilled" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "SparkMetric_CL\n| where $__timeFilter(TimeGenerated)\n| where  name_s  contains \"executor.memoryBytesSpilled\"\n| extend sname=split(name_s, \".\")  \n| summarize any(count_d)  by bin(TimeGenerated,  1m), strcat(sname[0],sname[1]) \n| order by TimeGenerated asc  nulls last",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "INREQS",
      "resourceGroup": "hotpath7",
      "resourceName": "hotpath-ehub-hotpath7",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 52 },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "taxirides_CL\n| where $__timeFilter(TimeGenerated)\n| where Level contains \"Error\"\n| project TimeGenerated , Message  \n",
      "resultFormat": "time_series",
      "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"
     },
     "azureMonitor": {
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}